// Al names database.
const database = {
    dbFirstName: [
        'Thiago',
        'Renato',
        'Marcos',
        'Leandro',
        'Milton',
        'Acácio',
        'Wanderson',
        'Rafael',
        'Denis',
        'Jean',
        'Antonio',
        'Francisco',
        'Luiz',
        'Luis',
        'Paulo',
        'Carlos',
        'Manoel',
        'Pedro',
        'Raimundo',
        'Jorge',
        'Ana',
        'Leila',
        'Angela',
        'Vilma',
        'Andreia',
        'Paula',
        'Renata',
        'Raquel',
        'Sileide',
        'Luisa',
        'Priscila',
        'Pamela',
        'Vanuza',
        'Maria',
        'Natália',
        'Carla',
        'Bárbara',
        'Daniela',
        'Karen',
        'Karina'
    ],
    dbMiddleName: [
        'Vieira',
        'Bastos',
        'Andrade',
        'Matheus',
        'Braga',
        'Oliveira',
        'Moreno',
        'Militão',
        'Moreira',
        'Nunes',
        'Ferreira',
        'Rodrigues',
        'Alves',
        'Pereira',
        'Lima',
        'Ribeiro',
        'Cardoso',
        'Carvalho',
        'Pinto',
        'Natividade'
    ],
    dbLastName: [
        'dos Santos',
        'Silva',
        'do Nascimento',
        'de Jesus',
        'Gomes',
        'Filho',
        'Júnior',
        'Neto',
        'Vasconcelos',
        'Barcelos',
        'Martins',
        'Andrade',
        'Barbosa',
        'Barros',
        'Batista',
        'da Cruz',
        'Castro',
        'Freitas',
        'Marques',
        'Santana'
    ]
}

//console.log(database.dbFirstName.length);
//console.log(database.dbMiddleName.length);
//console.log(database.dbLastName.length);

module.exports = database;